#include "hash_tables.h"

/**
 * key_index - the key index generated by djb2 fucntion
 * @key: string key to generate index for
 * @size: the size of the hash table
 * Return: the index of the key in hash table
 */

unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int hash_value;

	hash_value = hash_djb2(key);
	hash_value = hash_value % size;

	return (hash_value);
}
